<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AP.Infra.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\contracts\AP.Contracts.Hardware\AP.Contracts.Hardware.csproj" />
    <ProjectReference Include="..\..\..\infra\AP.Infra.Hardware\AP.Infra.Hardware.csproj" />
    <ProjectReference Include="..\..\..\infra\AP.Infra.Resilience\AP.Infra.Resilience.csproj" />
    <ProjectReference Include="..\..\..\shared\AP.Shared.PluginSDK\AP.Shared.PluginSDK.csproj" />
    <ProjectReference Include="..\..\..\shared\AP.Shared.UI\AP.Shared.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="IoTClient" />
    <PackageReference Include="Polly.Core" />
  </ItemGroup>

</Project>
