<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\contracts\AP.Contracts.Report\AP.Contracts.Report.csproj" />
    <ProjectReference Include="..\..\contracts\AP.Contracts.Security\AP.Contracts.Security.csproj" />
    <ProjectReference Include="..\..\core\AP.Core\AP.Core.csproj" />
    <ProjectReference Include="..\..\shared\AP.Shared.Utilities\AP.Shared.Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FreeSql" />
    <PackageReference Include="FreeSql.Provider.Sqlite" />
    <PackageReference Include="MiniExcel" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

</Project>