<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\infra\AP.Infra.Database\AP.Infra.Database.csproj" />
    <ProjectReference Include="..\..\infra\AP.Infra.Report\AP.Infra.Report.csproj" />
    <ProjectReference Include="..\..\infra\AP.Infra.Resilience\AP.Infra.Resilience.csproj" />
    <ProjectReference Include="..\..\infra\AP.Infra.Hardware\AP.Infra.Hardware.csproj" />
    <ProjectReference Include="..\..\plugins\hardware\AP.Plugin.Plc.Mitsubishi\AP.Plugin.Plc.Mitsubishi.csproj" />
    <ProjectReference Include="..\..\plugins\hardware\AP.Plugin.Plc.Siemens\AP.Plugin.Plc.Siemens.csproj" />
    <ProjectReference Include="..\..\plugins\hardware\AP.Plugin.Plc.Omron\AP.Plugin.Plc.Omron.csproj" />
  </ItemGroup>

</Project>