<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\contracts\AP.Contracts.System\AP.Contracts.System.csproj" />
    <ProjectReference Include="..\..\..\contracts\AP.Contracts.Security\AP.Contracts.Security.csproj" />
    <ProjectReference Include="..\..\..\contracts\AP.Contracts.Hardware\AP.Contracts.Hardware.csproj" />
    <ProjectReference Include="..\..\..\core\AP.Core\AP.Core.csproj" />
    <ProjectReference Include="..\..\..\shared\AP.Shared.PluginSDK\AP.Shared.PluginSDK.csproj" />
    <ProjectReference Include="..\..\..\shared\AP.Shared.UI\AP.Shared.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FreeSql" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" />
  </ItemGroup>

</Project>
